"""Create posts table

Revision ID: 51279fc2d243
Revises: 6980c32818e0
Create Date: 2025-08-06 20:32:00.412384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51279fc2d243'
down_revision = '6980c32818e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    # ### end Alembic commands ###
